server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://dev-api.aparejos.net:3101/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true
    # The backoff_config section helps with retries
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10

scrape_configs:
  - job_name: node_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: clienttestapi
          hostname: "dev-webhook.aparejos.net"
          app: clienttestapi
          __path__: /app/logs/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<filename>[^/]+)\.log$'
      - regex:
          expression: '(?P<component>api|nginx|system)(?P<logtype>error|access|info)'
          source: filename
      - labels:
          component:
          logtype: